<?php

namespace Database\Seeders;










































































































































}    }        $this->command->line("✓ Sample articles attached");        $this->command->line("✓ 4 subcategories");        $this->command->line("✓ 4 main categories");        $this->command->info('Categories seeded successfully!');        }            }                $article->categories()->attach($science->id);            } else {                $article->categories()->attach($health->id);            } elseif ($index % 4 === 2) {                $article->categories()->attach($startup->id);                $article->categories()->attach($business->id);            } elseif ($index % 4 === 1) {                }                    $article->categories()->attach($ai->id);                if ($index % 2 === 0) {                $article->categories()->attach($technology->id);            if ($index % 4 === 0) {            // Attach to main categories        foreach ($articles as $index => $article) {                $articles = Article::published()->limit(5)->get();        // Attach sample articles to categories        ]);            'is_active'         => true,            'order'             => 2,            'parent_id'         => $business->id,            'icon'              => 'icon-finance',            'color'             => '#10b981',            'description'       => 'Financial markets and investments',            'slug'              => 'finance',            'name'              => 'Finance',        $finance = Category::create([        ]);            'is_active'         => true,            'order'             => 1,            'parent_id'         => $business->id,            'icon'              => 'icon-startup',            'color'             => '#10b981',            'description'       => 'Startup funding and launches',            'slug'              => 'startups',            'name'              => 'Startups',        $startup = Category::create([        // Subcategories for Business        ]);            'is_active'         => true,            'order'             => 2,            'parent_id'         => $technology->id,            'icon'              => 'icon-security',            'color'             => '#3b82f6',            'description'       => 'Cybersecurity news and threats',            'slug'              => 'cybersecurity',            'name'              => 'Cybersecurity',        $cybersecurity = Category::create([        ]);            'is_active'         => true,            'order'             => 1,            'parent_id'         => $technology->id,            'icon'              => 'icon-ai',            'color'             => '#3b82f6',            'description'       => 'AI and machine learning developments',            'slug'              => 'artificial-intelligence',            'name'              => 'Artificial Intelligence',        $ai = Category::create([        // Subcategories for Technology        ]);            'is_active'         => true,            'order'             => 4,            'meta_keywords'     => 'science, research, discovery, physics',            'meta_description'  => 'Explore latest scientific discoveries',            'meta_title'        => 'Science News - Research Updates',            'icon'              => 'icon-science',            'color'             => '#8b5cf6',            'description'       => 'Scientific discoveries and research',            'slug'              => 'science',            'name'              => 'Science',        $science = Category::create([        ]);            'is_active'         => true,            'order'             => 3,            'meta_keywords'     => 'health, wellness, medical, fitness',            'meta_description'  => 'Latest health and wellness news',            'meta_title'        => 'Health News - Wellness Updates',            'icon'              => 'icon-health',            'color'             => '#ec4899',            'description'       => 'Health and wellness information',            'slug'              => 'health',            'name'              => 'Health',        $health = Category::create([        ]);            'is_active'         => true,            'order'             => 2,            'meta_keywords'     => 'business, market, economy, finance',            'meta_description'  => 'Read latest business news and market analysis',            'meta_title'        => 'Business News - Market Updates',            'icon'              => 'icon-business',            'color'             => '#10b981',            'description'       => 'Business insights and market analysis',            'slug'              => 'business',            'name'              => 'Business',        $business = Category::create([        ]);            'is_active'         => true,            'order'             => 1,            'meta_keywords'     => 'technology, news, updates, trends',            'meta_description'  => 'Stay updated with the latest technology news and trends',            'meta_title'        => 'Technology News - Latest Updates',            'icon'              => 'icon-tech',            'color'             => '#3b82f6',            'description'       => 'Latest news and updates about technology trends',            'slug'              => 'technology',            'name'              => 'Technology',        $technology = Category::create([        // Main categories    {    public function run(): void     */     * Run the database seeds.    /**{class CategorySeeder extends Seederuse Illuminate\Database\Seeder;use App\Models\Category;use App\Models\Article;
